// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbKorOCs9ZUwZ9wcAfAUfOc3FSyGnotsA',
    appId: '1:430335870359:android:b9c70673271ed2d2c030d2',
    messagingSenderId: '430335870359',
    projectId: 'agrobanco-rural-hb',
    storageBucket: 'agrobanco-rural-hb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDioQkYoySy1iiXPj_9hQcSvXpu9lNch_w',
    appId: '1:430335870359:ios:a2c316c281ceda51c030d2',
    messagingSenderId: '430335870359',
    projectId: 'agrobanco-rural-hb',
    storageBucket: 'agrobanco-rural-hb.firebasestorage.app',
    iosBundleId: 'com.example.agrobancoHomeBanking',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnJ_hxrJ6sGumfZT2uc8daPoGEC1Cwt9U',
    appId: '1:430335870359:web:6c888c990d964f74c030d2',
    messagingSenderId: '430335870359',
    projectId: 'agrobanco-rural-hb',
    authDomain: 'agrobanco-rural-hb.firebaseapp.com',
    storageBucket: 'agrobanco-rural-hb.firebasestorage.app',
  );

}